pr:
  - master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.13'
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: 3.6
  displayName: 'Use Python 3.6'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    pip install pytest-azurepipelines
  displayName: 'install pytest-azurepipelines'
- script: tox -e py
  displayName: Install package and run tests

- task: PublishTestResults@2
  inputs:
    testResultsFiles: .tox/results.xml
    testRunTitle: Python $(PYTHON_VERSION)

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: .tox/coverage.xml
    reportDirectory: .tox/coverage